### DISCUSSION TITLE
Any chance at support for the Q930C? Or perhaps it works and I'm not installing this correctly?

### DISCUSSION THREAD

**Discussion by dslugPX** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#64] [Q&A]
Just got a Q930C and was hoping to be able to control inputs and volume programmatically. 

I saw it wasn't on the list and was hoping it just wasn't tested yet, but I installed the add on this morning and updated configuration.yaml as noted in the readme, restarted and.... Nothing.

I can see it using the regular smarthingsAPI add on - but there is no entity even created after adding to YAML so I'm presuming the integration simply can't see it. 

Be real curious if maybe I'm just missing a step though. 
What I did so far: 
Install the repe into HACS
Downloaded into HACS
Updated configuration.yaml with: 

```yaml
media_player:
  - platform: smartthings_soundbar
    name: SuiteSoundbar
    api_key: "REDACTED"
    device_id: "REDACTED"
    max_volume: 100
```
    
Restarted Home Assistant.

Tried to add a card with the entity, but it doesn't exist. 

Thanks for any help!
