### ISSUE TITLE
No media_player after installation and config

### ISSUE THREAD

**Issue by elgeniskogen** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#21]
Hi,

Thanks for doing this great work and for sharing! I hope you enjoyed the coffee and are able to help me.

I have a Samsung HW-Q960A (think same as 950 in US) installed and running fine in SmartThings app. I am able to use the SmartThings integration and access all my devices in SmartThings. For the Soundbar I can only see status and turn on/Off, so I installed your component with HACS. I have booted HA after install in HACS and after config, but the media_player don´t show up among the entities. I have turned on debug-logging for custom_components.smartthings_soundbar, but there are no messages in the log. 

My configuration.yaml is liek this

```
media_player:
  - platform: smartthings_soundbar
    name: Soundbar
    api_key: "fcd9983f-fb9d-4d91-b939-XXXXXXXXXXXX"
    device_id: "93e650eb-9e34-f161-8667-XXXXXXXXXXXXX"

logger:
  default: warning
  logs:
    custom_components.smartthings_soundbar: debug

```

If I am not able to select input-source with your great component, I am afraid I will have to retrun the soundbar. So your help will be highly appreacted!!!

best regards

Erik :-)
